development:
  adapter: sqlite3
  encoding: utf8
  pool: 5
  timeout: 5000
  database: db/development.sqlite3
  template: template0

test:
  adapter: sqlite3
  encoding: utf8
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
  template: template0
