# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 006036bcc5738ccffd7a2aa07efbfbfa6e5ace3609c10d2e294a755dd22f9618699cd0386dfe85a281f3342fd04d06bcf2ee7cd11ba66988a8a98958989dd52c

test:
  secret_key_base: 2ad904c8ed5c10d3dfd525dc833231d3b4e738e82d27487d4fa26b4d780503c49cc8cfd0fc5b8bbe623fbf0352d5af6f2b91bf5a856a96982eb4b29cef32e995

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
